import React, {useState, useEffect} from "react";

const languages = [
    {code: 'af', name: 'Afrikaans'},
    {code: 'sq', name: 'Albanian'},
    {code: 'gm', name: 'Alemannic'},
    {code: 'am', name: 'Amharic'},
    {code: 'grc', name: 'Ancient_Greek'},
    {code: 'an', name: 'Aragonese'},
    {code: 'hy', name: 'Armenian'},
    {code: 'ast', name: 'Asturian'},
    {code: 'az', name: 'Azerbaijani'},
    {code: 'ban', name: 'Balinese'},
    {code: 'bn', name: 'Bangla'},
    {code: 'bx', name: 'Bashkir'},
    {code: 'eu', name: 'Basque'},
    {code: 'bav', name: 'Bavarian'},
    {code: 'be', name: 'Belarusian'},
    {code: 'be-tarask', name: 'Belarusian_Taraškievica_Orthography'},
    {code: 'bet', name: 'Betawi'},
    {code: 'bho', name: 'Bhojpuri'},
    {code: 'bs', name: 'Bosnian'},
    {code: 'pt-br', name: 'Brazilian_Portuguese'},
    {code: 'br', name: 'Breton'},
    {code: 'en-gb', name: 'British_English'},
    {code: 'bg', name: 'Bulgarian'},
    {code: 'my', name: 'Burmese'},
    {code: 'en-ca', name: 'Canadian_English'},
    {code: 'yue', name: 'Cantonese'},
    {code: 'ca', name: 'Catalan'},
    {code: 'ceb', name: 'Cebuano'},
    {code: 'ckb', name: 'Central_Kurdish'},
    {code: 'ce', name: 'Chechen'},
    {code: 'zh', name: 'Chinese'},
    {code: 'zh-cn', name: 'Chinese_China'},
    {code: 'zh-hk', name: 'Chinese_HongKong'},
    {code: 'zh-mo', name: 'Chinese_Macau'},
    {code: 'zh-my', name: 'Chinese_Malaysia'},
    {code: 'zh-sg', name: 'Chinese_Singapore'},
    {code: 'zh-tw', name: 'Chinese_Taiwan'},
    {code: 'cv', name: 'Chuvash'},
    {code: 'kw', name: 'Cornish'},
    {code: 'crh', name: 'Crimean_Tatar'},
    {code: 'hr', name: 'Croatian'},
    {code: 'cs', name: 'Czech'},
    {code: 'dag', name: 'Dagbani'},
    {code: 'da', name: 'Danish'},
    {code: 'nl', name: 'Dutch'},
    {code: 'eng', name: 'English'},
    {code: 'eo', name: 'Esperanto'},
    {code: 'et', name: 'Estonian'},
    {code: 'fo', name: 'Faroese'},
    {code: 'hif', name: 'Fiji_Hindi'},
    {code: 'fj', name: 'Fijian'},
    {code: 'fi', name: 'Finnish'},
    {code: 'fr', name: 'French'},
    {code: 'gl', name: 'Galician'},
    {code: 'gan', name: 'Gan'},
    {code: 'gan-simplified', name: 'Gan_Simplified_Han_Script'},
    {code: 'ka', name: 'Georgian'},
    {code: 'de', name: 'German'},
    {code: 'pih', name: 'Ghanaian_Pidgin'},
    {code: 'el', name: 'Greek'},
    {code: 'gn', name: 'Guarani'},
    {code: 'gcr', name: 'Guianan_Creole'},
    {code: 'gu', name: 'Gujarati'},
    {code: 'hak', name: 'Hakka_Chinese'},
    {code: 'ha', name: 'Hausa'},
    {code: 'he', name: 'Hebrew'},
    {code: 'hi', name: 'Hindi'},
    {code: 'hu', name: 'Hungarian'},
    {code: 'is', name: 'Icelandic'},
    {code: 'io', name: 'Ido'},
    {code: 'ilo', name: 'Iloko'},
    {code: 'smn', name: 'Inari_Sami'},
    {code: 'id', name: 'Indonesian'},
    {code: 'ia', name: 'Interlingua'},
    {code: 'iu', name: 'Inuktitut'},
    {code: 'ga', name: 'Irish'},
    {code: 'it', name: 'Italian'},
    {code: 'jam', name: 'Jamaican_Creole_English'},
    {code: 'ja', name: 'Japanese'},
    {code: 'jv', name: 'Javanese'},
    {code: 'kpy', name: 'Kabiye'},
    {code: 'kab', name: 'Kabyle'},
    {code: 'kl', name: 'Kalmyk'},
    {code: 'kn', name: 'Kannada'},
    {code: 'kk', name: 'Kazakh'},
    {code: 'ko', name: 'Korean'},
    {code: 'ku', name: 'Kurdish'},
    {code: 'ku-latn', name: 'Kurdish_Latin_Script'},
    {code: 'ky', name: 'Kyrgyz'},
    {code: 'lo', name: 'Lao'},
    {code: 'ltg', name: 'Latgalian'},
    {code: 'la', name: 'Latin'},
    {code: 'lv', name: 'Latvian'},
    {code: 'lfn', name: 'Lingua_Franca_Nova'},
    {code: 'lzh', name: 'Literary_Chinese'},
    {code: 'lt', name: 'Lithuanian'},
    {code: 'jbo', name: 'Lojban'},
    {code: 'lmo', name: 'Lombard'},
    {code: 'nds', name: 'Low_German'},
    {code: 'sax', name: 'Low_Saxon'},
    {code: 'smj', name: 'Lule_Sami'},
    {code: 'lb', name: 'Luxembourgish'},
    {code: 'mk', name: 'Macedonian'},
    {code: 'frr', name: 'Main_Franconian'},
    {code: 'mg', name: 'Malagasy'},
    {code: 'ms', name: 'Malay'},
    {code: 'jv', name: 'Malay_Jawi'},
    {code: 'ml', name: 'Malayalam'},
    {code: 'mt', name: 'Maltese'},
    {code: 'gv', name: 'Manx'},
    {code: 'mr', name: 'Marathi'},
    {code: 'mzn', name: 'Mazanderani'},
    {code: 'min', name: 'Minangkabau'},
    {code: 'xmf', name: 'Mingrelian'},
    {code: 'nan', name: 'Minnan'},
    {code: 'mir', name: 'Mirandese'},
    {code: 'mo', name: 'Moldovan'},
    {code: 'mn', name: 'Mongolian'},
    {code: 'nap', name: 'Neapolitan'},
    {code: 'ne', name: 'Nepali'},
    {code: 'fry', name: 'Northern_Frisian'},
    {code: 'se', name: 'Northern_Sami'},
    {code: 'nb', name: 'Norwegian_Bokmål'},
    {code: 'nn', name: 'Norwegian_Nynorsk'},
    {code: 'oc', name: 'Occitan'},
    {code: 'or', name: 'Odia'},
    {code: 'om', name: 'Oromo'},
    {code: 'pam', name: 'Pampanga'},
    {code: 'pap', name: 'Papiamento'},
    {code: 'ps', name: 'Pashto'},
    {code: 'fa', name: 'Persian'},
    {code: 'pcd', name: 'Picard'},
    {code: 'pms', name: 'Piedmontese'},
    {code: 'pl', name: 'Polish'},
    {code: 'pt', name: 'Portuguese'},
    {code: 'pa', name: 'Punjabi'},
    {code: 'qu', name: 'Quechua'},
    {code: 'ro', name: 'Romanian'},
    {code: 'ru', name: 'Russian'},
    {code: 'sa', name: 'Samogitian'},
    {code: 'sa', name: 'Scots'},
    {code: 'sa', name: 'Sanskrit'},
    {code: 'sa', name: 'Scottish_Gaelic'},
    {code: 'se1', name: 'Serbian'},
    {code: 'se2', name: 'Serbian_Cyrillic_script'},
    {code: 'se3', name: 'Serbian_Latin_script'},
    {code: 'se4', name: 'Serbo_Croatian'},
    {code: 'sh', name: 'Shona'},
    {code: 'si1', name: 'Sicilian'},
    {code: 'si2', name: 'Silesian'},
    {code: 'si3', name: 'Simplified_Chinese'},
    {code: 'si4', name: 'Sindhi'},
    {code: 'si5', name: 'Sinhala'},
    {code: 'si6', name: 'Skolt_Sami'},
    {code: 'si7', name: 'Slovak'},
    {code: 'si8', name: 'Slovenian'},
    {code: 'si9', name: 'Somali'},
    {code: 'si10', name: 'Spanish'},
    {code: 'si11', name: 'Standard_Moroccan_Tamazight'},
    {code: 'si12', name: 'Sundanese'},
    {code: 'si13', name: 'Swahili'},
    {code: 'si14', name: 'Swedish'},
    {code: 'tg', name: 'Tagalog'},
    {code: 'tg', name: 'Tajik_Cyrillic_script'},
    {code: 'tgc', name: 'Tajik'},
    {code: 'ta', name: 'Tamil'},
    {code: 'tt', name: 'Tatar'},
    {code: 'te', name: 'Telugu'},
    {code: 'th', name: 'Thai'},
    {code: 'ti', name: 'Tigrinya'},
    {code: 'tt', name: 'Tatar_Cyrillic_script'},
    {code: 'zh', name: 'Traditional_Chinese'},
    {code: 'tr', name: 'Turkish'},
    {code: 'udm', name: 'Udmurt'},
    {code: 'uk', name: 'Ukrainian'},
    {code: 'sr', name: 'Upper_Sorbian'},
    {code: 'ur', name: 'Urdu'},
    {code: 'ug', name: 'Uyghur'},
    {code: 'uz', name: 'Uzbek'},
    {code: 've', name: 'Venetian'},
    {code: 'vep', name: 'Veps'},
    {code: 'vi', name: 'Vietnamese'},
    {code: 'vo', name: 'Volapük'},
    {code: 'war', name: 'Waray'},
    {code: 'cy', name: 'Welsh'},
    {code: 'fy', name: 'Western_Frisian'},
    {code: 'pa', name: 'Western_Punjabi'},
    {code: 'wuu', name: 'Wu'},
    {code: 'xh', name: 'Xhosa'},
    {code: 'yao', name: 'Yakut'},
    {code: 'yi', name: 'Yiddish'},
    {code: 'yo', name: 'Yoruba'},
    {code: 'zza', name: 'Zazaki'},
    {code: 'zu', name: 'Zulu'}
];



export const Settings = ({selectedLanguage, setSelectedLanguage}) =>{

    const handleChange = (event) =>{
        const newLanguage= event.target.value;
        setSelectedLanguage(newLanguage);
        // console.log("in settings: ", selectedLanguage);
    }

    useEffect(() => {
        console.log("Updated selectedLanguage after render: ", selectedLanguage);
    }, [selectedLanguage]);

    return(
        <div className="settings">
            <select 
                className="language-dropdown"
                id="language-dd"
                value={selectedLanguage}
                onChange={handleChange}
            >
                {languages.map((language) => (
                <option key= {language.code} value ={language.name}>
                    {language.name}
                </option>
            ))}</select>
        </div>
    )
}